### ISSUE TITLE
Spotify restarts hidden

### ISSUE THREAD

**Issue by EnricoBara** [simonmeusel/MuteSpotifyAds#27]
After the auto-restart, spotify icon becomes "dim" as it starts hidden.

**Comment by qmnl** [comment]
Thank you reporting an issue, but what is the problem? It starting in the background is intended.

**Comment by EnricoBara** [comment]
Uhm maybe I was wrong... There's not a way to start an app minimized but just hidden...

**Comment by simar7** [comment]
Would it be possible to have an option to start it back in foreground?

**Comment by qmnl** [comment]
There is already an option to start Spotify in the fore/background on launch. I'm against an option to start it in the foreground on relaunch, because there are already a lot of options available and I think this option would not have many use cases. If you still need it, you can change it in the source code, should be as easy as removing the `--background` and the running it with XCode.
